version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_news
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodbpassword

  flask_app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:mongodbpassword@mongodb:27017/mydatabase

volumes:
  mongo_data:
